task:
  name: Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  release_script:
    - chmod +x "$PWD/bin/7z"
    - brew install 7zip
    - mkdir -p "$HOME/bin"
    - curl https://mise.jdx.dev/install.sh | sh
    - echo "PATH=$HOME/.local/share/mise/bin:$PATH" >> $CIRRUS_ENV
    - echo "PATH=$HOME/.local/share/mise/shims:$PATH" >> $CIRRUS_ENV
    - echo "MISE_TRUSTED_CONFIG_PATHS="$PWD/.mise.toml"
    - echo "MISE_YES="yes"
    - export PATH=$HOME/bin:$PATH
    - mise install
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - chmod +x priv/cmd
    - PATH="$PWD/bin:$PATH" MIX_ENV=prod mix release
  binary_artifacts:
    path: burrito_out/*
