name: Homebrew

on:
  push:
    tags:
      - 'v*'

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.GH_API_TOKEN}}
          no_fork: true
          tap: elixir-tools/tap
          formula: next-ls
